import "./globals.css";
import {
  inter,
  dmSans,
  montserrat,
  manrope,
  playfairDisplay,
  plusJakartaSans,
  robotoMono
} from './fonts';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${dmSans.variable} ${montserrat.variable} ${manrope.variable} ${playfairDisplay.variable} ${plusJakartaSans.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
